// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPEbCMY-Rvgoha1TnCaBC-bymU4gt6yMg',
    appId: '1:561193315321:web:d3440587ba66df92b82b28',
    messagingSenderId: '561193315321',
    projectId: 'com-mads-pushex',
    authDomain: 'com-mads-pushex.firebaseapp.com',
    storageBucket: 'com-mads-pushex.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByV-MayzgCOBzAKjqIgONJoHBqbfg3QSI',
    appId: '1:561193315321:android:1a607508d1754680b82b28',
    messagingSenderId: '561193315321',
    projectId: 'com-mads-pushex',
    storageBucket: 'com-mads-pushex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmRFlPn5kTAKPXL3PM90Y8jRY7VtFiWuA',
    appId: '1:561193315321:ios:dc9397f987ffa34cb82b28',
    messagingSenderId: '561193315321',
    projectId: 'com-mads-pushex',
    storageBucket: 'com-mads-pushex.appspot.com',
    iosClientId: '561193315321-evl75tujkqpkprmv6lbgmv562sf5g29t.apps.googleusercontent.com',
    iosBundleId: 'org.mads.pushex.pushEx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmRFlPn5kTAKPXL3PM90Y8jRY7VtFiWuA',
    appId: '1:561193315321:ios:dc9397f987ffa34cb82b28',
    messagingSenderId: '561193315321',
    projectId: 'com-mads-pushex',
    storageBucket: 'com-mads-pushex.appspot.com',
    iosClientId: '561193315321-evl75tujkqpkprmv6lbgmv562sf5g29t.apps.googleusercontent.com',
    iosBundleId: 'org.mads.pushex.pushEx',
  );
}
